[tool.poetry]
name = "photo_organiser"
version = "0.1.0"
description = "Python script to organise and de-duplicate photos, taking manually named directories into account along the way."
authors = ["Sam Martin <sam@abitmoredepth.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
